// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_DV.Models;

#nullable disable

namespace Test_DV.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240822183558_app2")]
    partial class app2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Test_DV.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Test_DV.Models.DepartmentFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IdDepartment")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdFacility")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdStaff")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartment");

                    b.HasIndex("IdFacility");

                    b.HasIndex("IdStaff");

                    b.ToTable("DepartmentFacilities");
                });

            modelBuilder.Entity("Test_DV.Models.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("Test_DV.Models.ImportHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImportHistories");
                });

            modelBuilder.Entity("Test_DV.Models.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("Test_DV.Models.MajorFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IdDepartmentFacility")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMajor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartmentFacility");

                    b.HasIndex("IdMajor");

                    b.ToTable("MajorFacilities");
                });

            modelBuilder.Entity("Test_DV.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountFe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountFpt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Test_DV.Models.StaffMajorFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IdMajorFacility")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdStaff")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IdMajorFacility");

                    b.HasIndex("IdStaff");

                    b.ToTable("StaffMajorFacilities");
                });

            modelBuilder.Entity("Test_DV.Models.DepartmentFacility", b =>
                {
                    b.HasOne("Test_DV.Models.Department", "Department")
                        .WithMany("DepartmentFacilities")
                        .HasForeignKey("IdDepartment");

                    b.HasOne("Test_DV.Models.Facility", "Facility")
                        .WithMany("DepartmentFacilities")
                        .HasForeignKey("IdFacility");

                    b.HasOne("Test_DV.Models.Staff", "Staff")
                        .WithMany("DepartmentFacilities")
                        .HasForeignKey("IdStaff");

                    b.Navigation("Department");

                    b.Navigation("Facility");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Test_DV.Models.MajorFacility", b =>
                {
                    b.HasOne("Test_DV.Models.DepartmentFacility", "DepartmentFacility")
                        .WithMany("MajorFacilities")
                        .HasForeignKey("IdDepartmentFacility");

                    b.HasOne("Test_DV.Models.Major", "Major")
                        .WithMany("MajorFacilities")
                        .HasForeignKey("IdMajor");

                    b.Navigation("DepartmentFacility");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("Test_DV.Models.StaffMajorFacility", b =>
                {
                    b.HasOne("Test_DV.Models.MajorFacility", "MajorFacility")
                        .WithMany("StaffMajorFacilities")
                        .HasForeignKey("IdMajorFacility");

                    b.HasOne("Test_DV.Models.Staff", "Staff")
                        .WithMany("StaffMajorFacilities")
                        .HasForeignKey("IdStaff");

                    b.Navigation("MajorFacility");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Test_DV.Models.Department", b =>
                {
                    b.Navigation("DepartmentFacilities");
                });

            modelBuilder.Entity("Test_DV.Models.DepartmentFacility", b =>
                {
                    b.Navigation("MajorFacilities");
                });

            modelBuilder.Entity("Test_DV.Models.Facility", b =>
                {
                    b.Navigation("DepartmentFacilities");
                });

            modelBuilder.Entity("Test_DV.Models.Major", b =>
                {
                    b.Navigation("MajorFacilities");
                });

            modelBuilder.Entity("Test_DV.Models.MajorFacility", b =>
                {
                    b.Navigation("StaffMajorFacilities");
                });

            modelBuilder.Entity("Test_DV.Models.Staff", b =>
                {
                    b.Navigation("DepartmentFacilities");

                    b.Navigation("StaffMajorFacilities");
                });
#pragma warning restore 612, 618
        }
    }
}
